# Generated by Django 5.2.12 on 2026-06-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_default_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('enterprise', 'Enterprise')], default='standard', help_text="Determines which Django-Q worker cluster the org's analyses are routed to.", max_length=20),
        ),
    ]
