# Generated by Django 5.2.12 on 2026-03-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='tag',
        ),
        migrations.AddField(
            model_name='document',
            name='last_record_holder',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='tract_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
