# Generated by Django 5.2.12 on 2026-04-03 02:41

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_document_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=apps.documents.models.document_upload_path),
        ),
    ]
