# Generated by Django 5.2.12 on 2026-04-03 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_default_org'),
        ('documents', '0004_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfolder',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='accounts.organization'),
        ),
    ]
