# Generated by Django 5.2.12 on 2026-04-23 02:08

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentfolder_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=500, upload_to=apps.documents.models.document_upload_path),
        ),
    ]
