# Generated by Django 5.2.12 on 2026-03-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotanalysis',
            name='ai_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='default_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
