# Generated by Django 5.2.12 on 2026-03-10 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_cotanalysis_ai_model_usersettings_default_model'),
        ('documents', '0002_remove_document_tag_document_last_record_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotanalysis',
            name='generated_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_from_analysis', to='documents.document'),
        ),
        migrations.AddField(
            model_name='cotanalysis',
            name='output_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document')], default='pdf', max_length=10),
        ),
    ]
