# Generated by Django 5.2.12 on 2026-03-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_cotanalysis_generated_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotanalysis',
            name='progress_step',
            field=models.CharField(blank=True, choices=[('queued', 'Queued'), ('extracting_text', 'Extracting text'), ('building_prompt', 'Building prompt'), ('calling_ai', 'Calling AI'), ('generating_document', 'Generating document'), ('complete', 'Complete'), ('failed', 'Failed')], default='queued', max_length=30),
        ),
    ]
