# Generated by Django 5.2.12 on 2026-03-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_cotanalysis_progress_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='custom_prompt',
            field=models.TextField(blank=True, default='', help_text='Custom instructions for the AI when using this template. Overrides the default form template instructions section of the prompt.'),
        ),
    ]
