# Generated by Django 5.2.12 on 2026-04-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_formtemplate_custom_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotanalysis',
            name='prompt_text',
            field=models.TextField(blank=True, default='', help_text='Full prompt sent to the AI (text portions only, for debugging).'),
        ),
    ]
