# Generated by Django 5.2.12 on 2026-04-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_cotanalysis_prompt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotanalysis',
            name='progress_step',
            field=models.CharField(blank=True, choices=[('queued', 'Queued'), ('extracting_text', 'Extracting text'), ('building_prompt', 'Building prompt'), ('calling_ai', 'Calling AI'), ('generating_document', 'Generating document'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=30),
        ),
        migrations.AlterField(
            model_name='cotanalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
