# Generated by Django 5.2.12 on 2026-04-02 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_membership'),
        ('analysis', '0007_add_cancelled_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anthropic_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('openai_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('gemini_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('default_provider', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)'), ('gemini', 'Google (Gemini)')], default='anthropic', max_length=20)),
                ('default_model', models.CharField(blank=True, default='', max_length=100)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_settings', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'organization settings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
