# Generated by Django 5.2.12 on 2026-04-03 02:41

import apps.analysis.models
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_organizationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='file',
            field=models.FileField(upload_to=apps.analysis.models._template_upload_path),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='anthropic_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='gemini_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='openai_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='anthropic_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='gemini_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='openai_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=''),
        ),
    ]
