# Generated by Django 5.2.12 on 2026-04-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_alter_formtemplate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotanalysis',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Number of input/prompt tokens consumed.'),
        ),
        migrations.AddField(
            model_name='cotanalysis',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Number of output/completion tokens consumed.'),
        ),
    ]
