# Generated by Django 5.2.12 on 2026-06-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_formtemplate_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotanalysis',
            name='header_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
