# Generated by Django 5.2.12 on 2026-06-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_cotanalysis_header_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotanalysis',
            name='header_extracted',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
