# Generated by Django 5.2.12 on 2026-06-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_remove_formtemplate_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='lock_member_api_keys',
            field=models.BooleanField(default=False),
        ),
    ]
